### ISSUE TITLE
App not started by the time handlers are called?

### ISSUE THREAD

**Issue by abingham** [yunstanford/pytest-sanic#13] opened 2018-02-27 15:00 UTC
I'm trying to sort out an error I'm seeing when I use this package. In one of my handlers I access `request.app.loop`, but sanic is reporting that I can only access the loop after the app is started. Here's the error:

```
  File "/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/sanic/app.py", line 556, in handle_request
    response = await response
  File "/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/repl_container_python-1.0.0-py3.6.egg/repl_container_python/handlers.py", line 64, in create_repl_handler
    loop=request.app.loop,
  File "/Users/abingham/.virtualenvs/cyber-dojo/lib/python3.6/site-packages/sanic/app.py", line 73, in loop
    'Loop can only be retrieved after the app has started '
sanic.exceptions.SanicException: Loop can only be retrieved after the app has started running. Not supported with `create_server` function
```

I'm using a test fixture following the description in the pytest-sanic docs, and my configuration does in fact work for other handlers (i.e. those that don't access the loop). My fixture setup looks like this:

```python
import pytest
from sanic.websocket import WebSocketProtocol

import repl_container_python.app

@pytest.yield_fixture
def app():
    app = repl_container_python.app.create_app()
    yield app

@pytest.fixture(scope='function')
def test_cli(loop, app, test_client):
    client = test_client(app, protocol=WebSocketProtocol)
    return loop.run_until_complete(client)
```

And my test looks like this:
```python
class TestReplCreation:
    async def test_repl_creation_responds_with_201(self, test_cli):
        resp = await test_cli.post('/', data=b'[]')
        assert resp.status == 201
```

I'm seeing the failure in the handling of the `post()` call.

Any idea what's going on? I've look at the pytest-sanic implementation a bit, and it looks like maybe there's a missing call to `TestServer.start_server()`, but that's just educated guessing. I've followed the docs closely, so I feel like I'm missing something or just being dense.

**Comment by yunstanford** [comment] 2018-03-01 21:28
1. ```sanic.exceptions.SanicException: Loop can only be retrieved after the app has started running. Not supported with `create_server` function
``` =, this looks like you are retrieving `app.loop` before starting server.

2. try remove your `class TestReplCreation:` wrap.

**Comment by Relrin** [comment] 2018-03-01 21:31
Confirm that I have this issue as well, when my extension for AMQP is trying to connect to the RabbitMQ instance via sharing the same event loop.
As far as I understood from the code, it happens because each `TestClient` instance uses `_server` / `server` attribute for running a **copy** of your application, when the `TestClient.app` isn't run or initialized.

**Comment by yunstanford** [comment] 2018-03-01 21:38
do not reference `app.loop` or the `loop` anywhere before starting the server especially if your server using pre-fork model or so. it might cause the issue.

Or if i misunderstand the situation, can you post a snippet of your code so i can take a look ?

**Comment by Relrin** [comment] 2018-03-01 21:45
In my case I have the following pieces of code which are leads to this error:
1) using async function for getting transport and protocol [connect](https://github.com/OpenMatchmaking/microservice-auth/blob/master/auth/app/extensions/amqp.py#L35-L38)
2) Have a small worker that works with RabbitMQ:
- [Initialization with app](https://github.com/OpenMatchmaking/microservice-auth/blob/master/auth/app/__init__.py#L22-L23)
- [Call] (https://github.com/OpenMatchmaking/microservice-auth/blob/master/auth/app/rabbitmq/workers/register_microservice.py#L83-L87) to the connect function

And the test is pretty simple:
```python
from amqp_client import AmqpTestClient
from conftest import sanic_server  # NOQA

from app.rabbitmq.workers import RegisterMicroserviceWorker

REQUEST_QUEUE = RegisterMicroserviceWorker.QUEUE_NAME
REQUEST_EXCHANGE = RegisterMicroserviceWorker.REQUEST_EXCHANGE_NAME
RESPONSE_EXCHANGE = RegisterMicroserviceWorker.RESPONSE_EXCHANGE_NAME


async def test_register_microservice_returns_validation_error_for_missing_fields(sanic_server):
    client = AmqpTestClient(sanic_server.server.app, sanic_server.server.loop, REQUEST_QUEUE, REQUEST_EXCHANGE, '', RESPONSE_EXCHANGE)
    result = await client.send(payload={})
    print("response: {}".format(result))
    # ... some asserts here
```

**Comment by yunstanford** [comment] 2018-03-01 21:48
Thx, i'll take a loop tonight.

**Comment by yunstanford** [comment] 2018-03-02 01:58
@Relrin @abingham Thanks for reporting. Found the root cause, I'll push a fix for that.

**Comment by yunstanford** [comment] 2018-03-02 04:34
pushed a fix. let me know if still exists.

**Closed by yunstanford** 2018-03-02 04:34 UTC

**Comment by Relrin** [comment] 2018-03-02 09:03
@yunstanford I've checked the new release on my notebook with the same tests. Everything works good now. Thank you!

**Comment by abingham** [comment] 2018-03-02 09:23
Seems to work for me, too. Thanks!
