### ISSUE TITLE
with pytest-flake8 plugins conflict 

### ISSUE THREAD

**Issue by qulc** [yunstanford/pytest-sanic#5] opened 2017-08-02 04:52 UTC
`$ pytest tests/test_utils.py`
```
platform darwin -- Python 3.6.1, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
rootdir: /Users/qulc/Documents/PycharmProjects/upscale_hotel, inifile:
plugins: sanic-0.1.3, flake8-0.8.1, cov-2.5.1, celery-4.0.2
collected 12 items 

tests/test_utils.py ............

============== 12 passed in 2.37 seconds =========
```

`$ pytest tests/test_utils.py --flake8`
```
platform darwin -- Python 3.6.1, pytest-3.1.3, py-1.4.34, pluggy-0.4.0
rootdir: /Users/qulc/Documents/PycharmProjects/upscale_hotel, inifile:
plugins: sanic-0.1.3, flake8-0.8.1, cov-2.5.1, celery-4.0.2
collected 13 items 

tests/test_utils.py E............

____________ERROR at setup of FLAKE8-check _________________________

item = <Flake8Item 'tests/test_utils.py'>

    def pytest_runtest_setup(item):
        """
        append a loop fixture to all test func.
        """
>       if LOOP_KEY not in item.fixturenames:
E       AttributeError: 'Flake8Item' object has no attribute 'fixturenames'

../python3.6/site-packages/pytest_sanic/plugin.py:83: AttributeError
```

**Comment by yunstanford** [comment] 2017-08-02 05:30
Thanks for reporting. But i am thinking it's more like a `pytest-flake8` issue. The `item` pytest collect should always have the attribute `fixturenames`. 

Seems like `pytest-flake8` is not compatible with other plugins as well, `https://github.com/tholo/pytest-flake8/issues`. the issue is very similar.

Also, why not just call `flake8` directly ? it's just one command line, same as calling with `pytest-flake8`. I just don't see any benefit around that. maybe i am wrong since i am not familiar with that plugin.

**Comment by qulc** [comment] 2017-08-02 06:44
Thanks you reply.

this error is pytest-sanic raise.

https://github.com/yunstanford/pytest-sanic/blob/master/pytest_sanic/plugin.py#L83

**Comment by yunstanford** [comment] 2017-08-02 07:54
The error is raised by pytest-sanic, but it's because the `item`(Flake8Item) created by `pytest-flake8` is not `valid` or you can say `incompatible` and it has been collected by pytest collector.

Checkout here: https://github.com/tholo/pytest-flake8/issues/26, it's very similar issue.

pytest `setup` and `collector` for different plugins may be different/customized or even have conflict. but you can always disable/enable plugins. https://docs.pytest.org/en/latest/plugins.html#deactivating-unregistering-a-plugin-by-name

Again, a quick fix for this one could be easy. but i am not sure how valuable it is.

**Comment by yunstanford** [comment] 2017-08-02 08:03
also, let me know if u really wanna fix this. a quick fix could be easy.

and PR is always welcome.

**Comment by bow** [comment] 2017-11-25 17:24
Hi @yunstanford,

Related to this, I just stumbled on this issue when trying to use the `--doctest-modules` flag from `pytest` (which I believe is included in vanilla pytest):

```
item = <DoctestItem 'sentinel.utils.absorb_into'>

    def pytest_runtest_setup(item):
        """
        append a loop fixture to all test func.
        """
>       if LOOP_KEY not in item.fixturenames:
E       AttributeError: 'DoctestItem' object has no attribute 'fixturenames'
```

This is on pytest v3.2.1 and pytest-sanic v0.1.4. And I confirmed this was coming from `pytest-sanic` since running `py.test -p no:sanic --doctest-modules` work just fine. If it would help, I don't mind opening a PR for this.

**Comment by yunstanford** [comment] 2017-11-25 18:06
We can quick fix this. Go ahead and make a PR. Thanks. let me know if you have any question.

**Comment by yunstanford** [comment] 2017-11-26 04:53
Let's close this issue in favor of https://github.com/yunstanford/pytest-sanic/pull/9

**Closed by yunstanford** 2017-11-26 04:53 UTC
